version: '3.8'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: faculty_db
    volumes:
      - db_data:/var/lib/mysql
  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: secret
      DB_NAME: faculty_db
volumes:
  db_data:
